### ISSUE TITLE
Main character doesn't move on build unless Ignore Walkable Areas is checked.

### ISSUE THREAD

**Issue by LampGuitar1** [mapedorr/popochiu#61] opened 2023-06-22 01:17 UTC
In my older project and fresh new project; the main player can move about in the room fine when in Play(F5) mode but on exports (i'm exporting to .exe) the main player can't move from its initial position. I could only make the player move on builds if the Ignore Walkable Area is checked on the main player. Using godot 3.5.1

**Comment by mapedorr** [comment] 2023-06-22 12:54
Thanks. We'll give it a look.

**Comment by stickgrinder** [comment] 2023-12-17 17:30
@LampGuitar1 we can't reproduce this bug.

Are you sure you actually defined a Walkable Area in the room? The behaviour you're describing is exactly what happens if you try to move a character in a room without defined WAs.

I'm going to close this as a false-positive. If you have proper steps to reproduce, please add them here and reopen the issue.

Thanks

**Closed by stickgrinder** 2023-12-17 17:30 UTC
Labels: bug
