### ISSUE TITLE
Can't create markers in 2.0 alpha

### ISSUE THREAD

**Issue by papernoise** [mapedorr/popochiu#83] opened 2023-09-30 16:03 UTC
Godot version: 4.1.1
Popochiu version: 2.0 alpha

When I click on "Create Region" in the Popochiu dock, nothing happens. I don't even get an error message.

**Comment by stickgrinder** [comment] 2023-12-17 17:42
@papernoise sorry but we're not sure if you're talking about not being able to create markers (in that case it's a missing feature) or regions as you mentioned in the description (in that case it's a bug).

Regions seem to work flawlessly in every branch now.

Let me know so that I can handle this feature.

**Comment by papernoise** [comment] 2023-12-18 07:37
Sorry, I got confused and wrote "regions" instead of "markers", but I really meant "markers".
But I see this is a known missing feature, so we can close this.

**Comment by stickgrinder** [comment] 2023-12-18 08:21
Duplicate of #112

**Comment by stickgrinder** [comment] 2023-12-18 08:21
@papernoise thanks for the info. I'm going to close this!

**Closed by stickgrinder** 2023-12-18 08:21 UTC
Labels: bug
